services:
  mysql:
    image: mysql:8.4
    container_name: zr-access-mysql
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zr_access_portal
    ports:
      - "33306:3306"
    volumes:
      - zr-access-mysql:/var/lib/mysql

volumes:
  zr-access-mysql:
